title: Allen Lee
author: Allen
email: allenleein@gmail.com
description: > # this means to ignore newlines until "show_exerpts:"
  Nothing normal ever change a damn thing
show_excerpts: false # set to true to show excerpts on the homepage

paginate: 10
paginate_path: "/blog/page:num/"

tag_permalink_style: pretty
tag_page_layout: tag_page
tag_page_dir: tag

# jekyll-dash date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
dash:
  date_format: "%b %-d, %Y"

  disqus:
    shortname: 

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/allenleein
      icon: twitter-square
      color: cyan
    - url: https://github.com/allenleein
      icon: github-square
      color: green
    - url: https://soundcloud.com/gamestheory
      icon: soundcloud
      color: orange
# Build settings
theme: jekyll-dash

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-paginate
 - liquid-md5
 - jekyll/tagging
